#include "Plugin.h"

//SKSE Plugin Entry Point (CommonLib-variant-specific)
//This is the only translation unit that exports an SKSE entry symbol. All
//initialization is in Plugin::OnLoad, which is backend-agnostic.
//
//libxse/commonlibsse:
//SKSE_PLUGIN_LOAD exports SKSEPlugin_Load. The SKSEPlugin_Version block is
//generated by the xmake `commonlibsse.plugin` rule (commonlibsse-plugin.cpp.in).
//
//CommonLibSSE-NG:
//SKSE_PLUGIN_LOAD still exports SKSEPlugin_Load; NG additionally emits a
//SKSEPlugin_Query export so SKSE VR's legacy loader recognizes the DLL.
//Declaring the SKSEPlugin_Version block (with VR added to the compatible
//runtimes) also belongs here once NG is wired in.

SKSE_PLUGIN_LOAD(const SKSE::LoadInterface* a_skse)
{
	return Plugin::OnLoad(a_skse);
}
